### ISSUE TITLE
where can I see this paper?

### ISSUE THREAD

**Issue by zhangdong1992** [wagner-group/dual-domain-at#1]
Hi, I can't find this paper through Google search. When will it be released?

**Comment by chawins** [comment]
The workshop version is accepted to ICML UDL 2021. Here's the link: http://www.gatsby.ucl.ac.uk/~balaji/udl2021/accepted-papers/UDL2021-paper-048.pdf.
We are still working on the full version right now so it might take a bit longer to be released. We will post it on arXiv once it's ready.
